id = "django-html"
name = "Django HTML"
version = "0.0.1"
schema_version = 1
authors = ["Rafay Ahmad <rafayahmad1425@gmail.com>"]
description = "Support for Django Template Language"
repository = "https://github.com/RafayAhmad7548/zed-django-html"


[grammars.django-html]
repository = "https://github.com/interdependence/tree-sitter-htmldjango" 
rev = "3a643167ad9afac5d61e092f08ff5b054576fadf"
